description: <p><a href="http://www.openmicroscopy.org/Schemas/">OME-XML</a> is a
  vendor-neutral file format for biological image data, with an emphasis on metadata
  supporting light microscopy. It can be used as a data file format in its own right,
  or as a way of encoding metadata within a TIFF or BigTIFF file (for which purpose
  there is the <a href="http://www.openmicroscopy.org/site/support/file-formats/ome-tiff/ome-tiff-specification">OME-TIFF</a>
  specification).</p><p>The standard is maintained by the Open Microscopy Environment
  Consortium, and was last updated in June 2012.</p>
identifiers:
- id: msc:m29
  scheme: RDA-MSCWG
keywords:
- Animal diseases
- Physiology
- Zoology
- Plant physiology
- Plant diseases
- Cell biology
locations:
- type: document
  url: http://www.openmicroscopy.org/Schemas/
- type: website
  url: http://www.openmicroscopy.org/site/support/file-formats
relatedEntities:
- id: msc:g17
  role: user
- id: msc:g62
  role: user
title: OME-XML (Open Microscopy Environment XML)
